### ISSUE TITLE
packet_ssh_key.host_key: Key already exists

### ISSUE THREAD

**Issue by vielmetti** [packet-labs/Packet-Terraform-Project-Boilerplate#6]
I am running this on my macOS system and run into this error:

```
Error: Error applying plan:
1 error(s) occurred:
* packet_ssh_key.host_key: 1 error(s) occurred:
* packet_ssh_key.host_key: Key already exists
```

I don't see any mention of this at https://www.terraform.io/docs/providers/packet/r/ssh_key.html

**Comment by johnstudarus** [comment]
If you already have the SSH key uploaded into the Packet project, you can't upload it again.

I recommend using a different key and setting it in terraform.vars.

```
public_key_filename = "./id_rsa.pub"
private_key_filename = "./id_rsa"
```

And then create that new key (ssh-keygen) using a different comment name than the key you've already uploaded.

**Comment by johnstudarus** [comment]
Added wording in README explaining the workaround if your key is already uploaded.
